### ISSUE TITLE
Kundens valg af forsendelsesmetode

### ISSUE THREAD

**Issue by mikaelbirkelundjohansen** [discimport/discimport.dk#13]
Postdanmark har igen ændret priser og service på forsendelser/levering.
Vi har brug for at kunden kan tilvælge at pakken skal være med "omdeling" hvilket skal koste et gebyr på 15 kr.
de skal også kunne vælge "flexlevering" uden gebyr.

**Comment by lsolesen** [comment]
Priserne for vores forsendelse er i øjeblikket for dyr synes jeg. Hvad siger du?

**Comment by mikaelbirkelundjohansen** [comment]
hmm, jeg synes forsendelsespriserne skal afspejle hvad det koster at sende. Vi sender pakkepost og det er dyrt. alternativt skal vi sætte priserne lidt op? prisen på omdeling er dyr, men hvis ikke der skal være omdeling på eller der er flexlevering kan vi gøre det billigere.

**Comment by lsolesen** [comment]
Mit problem er i øjeblikket at vi sælger alt for lidt, hvilket gør hosting, pbs mv. for dyr. Vi tager 21 kroner mere i forsendelse end vores konkurrenter. Det synes jeg er meget. Jeg har ikke tjekket priserne ift. vores konkurrenter, men går ud fra, at vi ligger lidt højere end dem også der.
