### ISSUE TITLE
tilføje tekst til ordre/faktura

### ISSUE THREAD

**Issue by mikaelbirkelundjohansen** [discimport/discimport.dk#14]
I det gamle system kunne vi tilføje en valgfri tekst til varer på ordren/faktruraen. Det ville være fedt at kunne igen i det nye system

**Comment by lsolesen** [comment]
Det kan man ikke. Men jeg kan lave en ny type produkt, hvor man kan få lov til at tilføje noget tekst. Hvor nødvendigt er det? Kan det ikke bare skrives på selve ordren, hvis der kommer et kommentarfelt?

**Comment by mikaelbirkelundjohansen** [comment]
et kommentarflet vil nok kunne gøre det
