### ISSUE TITLE
rabat i manuelle ordrer

### ISSUE THREAD

**Issue by mikaelbirkelundjohansen** [discimport/discimport.dk#19]
JEg kan ikke se den rabat (fixed amount discount) som jeg tilføjer i ordrerne? og ligeledes heller ikke slette dem igen?
JEg har brug for at redigere rabatten i ordre nr. 39

Denne her er magen til den tidligere, men den fik jeg lukket lidt for tidligt ;-)

**Comment by lsolesen** [comment]
Tror der er lavet noget på dette i Commerce Kickstart. Reopen, hvis det fortsat er et problem.
