### ISSUE TITLE
landenavn skjult i feltet

### ISSUE THREAD

**Issue by mikaelbirkelundjohansen** [discimport/discimport.dk#25]
dropdownfeltet med landenavne skjuler teksten

**Comment by lsolesen** [comment]
På hvilken side?

**Comment by mikaelbirkelundjohansen** [comment]
den side hvor kunden skal indskrive sine oplysninger ved betaling

**Comment by lsolesen** [comment]
Tjek lige igen - og luk, hvis ikke længere det er et issue.

**Comment by lsolesen** [comment]
Kan ikke længere reproducere.
