### ISSUE TITLE
ingen bekræftelsesmail når man har lagt ordren

### ISSUE THREAD

**Issue by mikaelbirkelundjohansen** [discimport/discimport.dk#27]
Skal der ikke komme en bekræftelse på mail når man har placeret en ordre. jeg har placeret en med bankbetaling, men fik ingen mail.

**Comment by mikaelbirkelundjohansen** [comment]
Der kom heller ikke nogen mail da odrestatussen blev opdateret?

**Comment by lsolesen** [comment]
Har du placeret ordren i selve butikken - eller manuelt?

**Comment by lsolesen** [comment]
http://drupal.org/node/1751310

**Comment by lsolesen** [comment]
Der kommer ikke e-mail, når status på ordren bliver opdateret. Men nu skulle ordremailen gerne blive sendt ud.
