### ISSUE TITLE
Ordre @numer

### ISSUE THREAD

**Issue by mikaelbirkelundjohansen** [discimport/discimport.dk#29]
skal der ikke står ordrens nummer stedet for Ordre @numer. teksten giver ikke rigtig nogen mening, men det ville være rart hvis ordre nummeret kunne står der.

**Comment by lsolesen** [comment]
Det er et oversættelsesproblem som jeg har opdateret på localize.drupal.org. Så snart de pakker nye oversættelsespakker bliver det opdateret.
