### ISSUE TITLE
fejl ved opdatering af status ordre 57

### ISSUE THREAD

**Issue by mikaelbirkelundjohansen** [discimport/discimport.dk#31]
fik denne fejl da jeg ville opdatere status fra afventer til behandler:
[{"command":"settings","settings":{"basePath":"\/","pathPrefix":"","ajaxPageState":{"theme":"commerce_kickstart_theme","theme_token":"EetYn8YUCjICV7DCYg3Ti3DMtO50sFCBjiGjoKOxvYg"}},"merge":true}]

**Comment by lsolesen** [comment]
Hm, et ved jeg sørme ikke lige. Har du en ordre, hvor jeg kan få lov til at ændre status uden, at der sker noget slemt?

**Comment by lsolesen** [comment]
Kan ikke reproducere denne.
