### ISSUE TITLE
fejl ved forsendelsesomkostninger (ordre 59)

### ISSUE THREAD

**Issue by mikaelbirkelundjohansen** [discimport/discimport.dk#32]
Expressforsendelse? 15$ hvorfor i dollars? butikken kan ikke omregne nogen kurs, så betalingen bliver kun 15 kr.???

**Comment by lsolesen** [comment]
Husk at du skal oprette det under projektet discimport-deploy og ikke under dette projekt. 

Ham der har bestilt ekspresforsendelse har bestilt i de 10 minutter det var slået til efter opgraderingen. Det er han jo bare heldig med :)

**Comment by lsolesen** [comment]
Jeg lukker denne, da det ikke sker igen, da jeg har fjernet den forsendelsesmetode, hvilket dog skaber lidt problemer på ordren, som jeg lige forsøger at fikse.
