### ISSUE TITLE
bug ved ændring af status i ordre 105

### ISSUE THREAD

**Issue by mikaelbirkelundjohansen** [discimport/discimport.dk#34]
Fik denne besked da jeg forsøgte at ændre statussen fra behandler til udført i ordre 105. det er tilsyneladende kun når jeg står i fanebladet "rediger" og ikke hvis jeg står i fanebladet "vis" ?

[{"command":"settings","settings":{"basePath":"\/","pathPrefix":"","ajaxPageState":{"theme":"commerce_kickstart_theme","theme_token":"ILNXMO-AqqzbDvVDWcRFyjsC2YRyXSZWUH5AkEcnOlM"}},"merge":true}]

gik fra side http://discimport.dk/admin/commerce/orders/105/edit?destination=admin/commerce/orders%3Fq%3Dviews/ajax%26page%3D1

og fik side

http://discimport.dk/views/ajax?page=1

**Comment by lsolesen** [comment]
Kan ikke reproducere dette. Kan have været midlertidigt.
