### ISSUE TITLE
præcis hvormange af hvilke variationer der er på lager 

### ISSUE THREAD

**Issue by mikaelbirkelundjohansen** [discimport/discimport.dk#5]
kunden skal kunne se præcis hvor mange af hvilke variationer der er på lager - altså når man klikker ind på en vare, så skal man kunne vælge sin vare ud fra hvilken kombination imellem vægt og farve der er på lager, man skal også kunne se hvor mange der er på lager i hver kombination. Det er ens tor irritation for køberen  som det er nu, hvor man bliver mødt med en fejl ved at vælge en umulig kombination

**Comment by lsolesen** [comment]
Hvordan er dette relateret til gh-1?

**Comment by mikaelbirkelundjohansen** [comment]
hehe, det er vist det samme ;-) havde lige glemt at den var oprettet
